### ISSUE TITLE
有遇到过的吗

### ISSUE THREAD

**Issue by TheRepublicOfChina** [kenzok8/wall#26]
/home/ccp8964/H3399pc/lede/staging_dir/host/bin/fakeroot /home/ccp8964/H3399pc/lede/staging_dir/host/bin/bash /home/ccp8964/H3399pc/lede/scripts/ipkg-build -m "" /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/tuic-client-1.0.0/ipkg-aarch64_generic/tuic-client /home/ccp8964/H3399pc/lede/bin/packages/aarch64_generic/helloworld
Packaged contents of /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/tuic-client-1.0.0/ipkg-aarch64_generic/tuic-client into /home/ccp8964/H3399pc/lede/bin/packages/aarch64_generic/helloworld/tuic-client_1.0.0-1_aarch64_generic.ipk
echo "tuic-client" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/tuic-client.default.install
make[3]: Leaving directory '/home/ccp8964/H3399pc/lede/feeds/helloworld/tuic-client'
time: package/feeds/helloworld/tuic-client/compile#0.43#0.23#0.61
make[3]: Entering directory '/home/ccp8964/H3399pc/lede/feeds/helloworld/xray-core'
mkdir -p /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/ccp8964/H3399pc/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/Xray-core-1.8.9/.pkgdir/xray-core/. /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.xray-core_installed
echo "xray-core" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/xray-core.default.install
make[3]: Leaving directory '/home/ccp8964/H3399pc/lede/feeds/helloworld/xray-core'
time: package/feeds/helloworld/xray-core/compile#0.18#0.14#0.29
make[3]: Entering directory '/home/ccp8964/H3399pc/lede/feeds/packages/libs/nghttp2'
mkdir -p /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
echo '14' | cmp -s - /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libnghttp2.version || { echo '14' > /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libnghttp2.version;  } 
SHELL= flock /home/ccp8964/H3399pc/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/nghttp2-1.51.0/.pkgdir/libnghttp2/. /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.libnghttp2_installed
echo "libnghttp2" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/nghttp2.default.install
make[3]: Leaving directory '/home/ccp8964/H3399pc/lede/feeds/packages/libs/nghttp2'
time: package/feeds/packages/nghttp2/compile#0.18#0.12#0.27
make[3]: Entering directory '/home/ccp8964/H3399pc/lede/feeds/packages/net/curl'
mkdir -p /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
echo '4' | cmp -s - /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libcurl.version || { echo '4' > /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/libcurl.version;  } 
SHELL= flock /home/ccp8964/H3399pc/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/curl-8.6.0/.pkgdir/libcurl/. /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.libcurl_installed
echo "libcurl" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/curl.default.install
mkdir -p /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/ccp8964/H3399pc/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/curl-8.6.0/.pkgdir/curl/. /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.curl_installed
echo "curl" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/curl.default.install
make[3]: Leaving directory '/home/ccp8964/H3399pc/lede/feeds/packages/net/curl'
time: package/feeds/packages/curl/compile#0.21#0.15#0.32
make[3]: Entering directory '/home/ccp8964/H3399pc/lede/feeds/helloworld/luci-app-ssr-plus'
mkdir -p /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/ccp8964/H3399pc/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/luci-app-ssr-plus/.pkgdir/luci-app-ssr-plus/. /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.luci-app-ssr-plus_installed
echo "luci-app-ssr-plus" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/luci-app-ssr-plus.default.install
mkdir -p /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/ccp8964/H3399pc/lede/tmp/.root-copy.flock -c 'cp -fpR /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/luci-app-ssr-plus/.pkgdir/luci-i18n-ssr-plus-zh-cn/. /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/'
touch /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.luci-i18n-ssr-plus-zh-cn_installed
echo "luci-i18n-ssr-plus-zh-cn" >> /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/pkginfo/luci-app-ssr-plus.default.install
make[3]: Leaving directory '/home/ccp8964/H3399pc/lede/feeds/helloworld/luci-app-ssr-plus'
time: package/feeds/helloworld/luci-app-ssr-plus/compile#0.18#0.12#0.28
make[3]: Entering directory '/home/ccp8964/H3399pc/lede/feeds/kenzo/alist'
rm -f /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0/.built
touch /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/ccp8964/H3399pc/lede/tmp/go-build" GO_MOD_CACHE_DIR="/home/ccp8964/H3399pc/lede/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/alist-org/alist" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/alist-org/alist/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0" GO_BUILD_DIR="/home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0/.go_work/build" GO_BUILD_BIN_DIR="/home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0/.go_work/build/bin/linux_arm64" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/usr/share/gocode/src" GOOS="linux" GOARCH="arm64" GO386="" GOAMD64="" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0=alist-3.33.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -D_LARGEFILE64_SOURCE" CGO_CPPFLAGS="-I/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/include -I/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/include/fortify -I/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mcpu=generic -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0=alist-3.33.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -D_LARGEFILE64_SOURCE" CGO_LDFLAGS="-L/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0/.go_work/build" GOCACHE="/home/ccp8964/H3399pc/lede/tmp/go-build" GOMODCACHE="/home/ccp8964/H3399pc/lede/dl/go-mod-cache" GOENV=off GOTOOLCHAIN=local /usr/bin/env bash /home/ccp8964/H3399pc/lede/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1711551492' -linkmode external -extldflags '-L/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-w -s -X github.com/alist-org/alist/v3/internal/conf.Version=v3.33.0-aarch64 -X github.com/alist-org/alist/v3/internal/conf.WebVersion=3.33.0 -buildid '1711551492' -linkmode external -extldflags '-L/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/usr/lib -L/home/ccp8964/H3399pc/lede/staging_dir/toolchain-aarch64_generic_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets
../../../../../dl/go-mod-cache/github.com/!shelton!zhu/115driver@v1.0.22/pkg/driver/upload.go:20:2: no required module provides package github.com/SheltonZhu/115driver/pkg/crypto; to add it:
	go get github.com/SheltonZhu/115driver/pkg/crypto
../../../../../dl/go-mod-cache/github.com/gaoyb7/115drive-webdav@v0.1.8/115/api.go:10:2: no required module provides package github.com/gaoyb7/115drive-webdav/common; to add it:
	go get github.com/gaoyb7/115drive-webdav/common
../../../../../dl/go-mod-cache/github.com/gaoyb7/115drive-webdav@v0.1.8/115/client.go:16:2: no required module provides package github.com/gaoyb7/115drive-webdav/common/drive; to add it:
	go get github.com/gaoyb7/115drive-webdav/common/drive
../../../../../dl/go-mod-cache/github.com/pierrec/lz4/v4@v4.1.18/internal/lz4block/block.go:8:2: no required module provides package github.com/pierrec/lz4/v4/internal/lz4errors; to add it:
	go get github.com/pierrec/lz4/v4/internal/lz4errors
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/types.go:8:2: no required module provides package github.com/aws/aws-sdk-go/internal/sdkio; to add it:
	go get github.com/aws/aws-sdk-go/internal/sdkio
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/client/client.go:7:2: no required module provides package github.com/aws/aws-sdk-go/aws/client/metadata; to add it:
	go get github.com/aws/aws-sdk-go/aws/client/metadata
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/client/default_retryer.go:9:2: no required module provides package github.com/aws/aws-sdk-go/internal/sdkrand; to add it:
	go get github.com/aws/aws-sdk-go/internal/sdkrand
package github.com/alist-org/alist/v3
	imports github.com/alist-org/alist/v3/cmd
	imports github.com/alist-org/alist/v3/drivers
	imports github.com/alist-org/alist/v3/drivers/123
	imports github.com/aws/aws-sdk-go/aws/session
	imports github.com/aws/aws-sdk-go/aws/credentials/ssocreds
	imports github.com/aws/aws-sdk-go/service/sso
	imports github.com/aws/aws-sdk-go/aws/signer/v4
	imports github.com/aws/aws-sdk-go/private/protocol/rest
	imports github.com/aws/aws-sdk-go/private/protocol
	imports github.com/aws/aws-sdk-go/internal/sdkmath: build constraints exclude all Go files in /home/ccp8964/H3399pc/lede/dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/internal/sdkmath
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/ec2metadata/api.go:14:2: no required module provides package github.com/aws/aws-sdk-go/internal/sdkuri; to add it:
	go get github.com/aws/aws-sdk-go/internal/sdkuri
../../../../../dl/go-mod-cache/github.com/gin-gonic/gin@v1.9.1/binding/form_mapping.go:16:2: no required module provides package github.com/gin-gonic/gin/internal/json; to add it:
	go get github.com/gin-gonic/gin/internal/json
package github.com/alist-org/alist/v3
	imports github.com/alist-org/alist/v3/cmd
	imports github.com/charmbracelet/bubbles/table
	imports github.com/charmbracelet/bubbles/key
	imports github.com/charmbracelet/bubbletea
	imports github.com/mattn/go-isatty: build constraints exclude all Go files in /home/ccp8964/H3399pc/lede/dl/go-mod-cache/github.com/mattn/go-isatty@v0.0.19
../../../../../dl/go-mod-cache/github.com/rclone/rclone@v1.63.1/fs/fspath/path.go:12:2: no required module provides package github.com/rclone/rclone/fs/driveletter; to add it:
	go get github.com/rclone/rclone/fs/driveletter
../../../../../dl/go-mod-cache/github.com/rclone/rclone@v1.63.1/fs/rc/internal.go:21:2: no required module provides package github.com/rclone/rclone/lib/debug; to add it:
	go get github.com/rclone/rclone/lib/debug
../../../../../dl/go-mod-cache/github.com/multiformats/go-multihash@v0.2.3/registry.go:8:2: no required module provides package github.com/multiformats/go-multihash/register/all; to add it:
	go get github.com/multiformats/go-multihash/register/all
../../../../../dl/go-mod-cache/github.com/multiformats/go-multihash@v0.2.3/registry.go:9:2: no required module provides package github.com/multiformats/go-multihash/register/miniosha256; to add it:
	go get github.com/multiformats/go-multihash/register/miniosha256
../../../../../dl/go-mod-cache/github.com/libp2p/go-libp2p@v0.27.8/core/crypto/ecdsa.go:14:2: no required module provides package github.com/libp2p/go-libp2p/core/internal/catch; to add it:
	go get github.com/libp2p/go-libp2p/core/internal/catch
../../../../../dl/go-mod-cache/github.com/hirochachacha/go-smb2@v1.1.0/internal/msrpc/msrpc.go:7:2: no required module provides package github.com/hirochachacha/go-smb2/internal/utf16le; to add it:
	go get github.com/hirochachacha/go-smb2/internal/utf16le
../../../../../dl/go-mod-cache/github.com/blevesearch/bleve/v2@v2.3.10/geo/geo_s2plugin_impl.go:21:2: no required module provides package github.com/blevesearch/bleve/v2/util; to add it:
	go get github.com/blevesearch/bleve/v2/util
../../../../../dl/go-mod-cache/github.com/jackc/pgx/v5@v5.3.0/conn.go:11:2: no required module provides package github.com/jackc/pgx/v5/internal/anynil; to add it:
	go get github.com/jackc/pgx/v5/internal/anynil
../../../../../dl/go-mod-cache/github.com/pquerna/otp@v1.4.0/hotp/hotp.go:22:2: no required module provides package github.com/pquerna/otp/internal; to add it:
	go get github.com/pquerna/otp/internal
package github.com/alist-org/alist/v3
	imports github.com/alist-org/alist/v3/cmd
	imports github.com/charmbracelet/bubbles/table
	imports github.com/charmbracelet/bubbles/key
	imports github.com/charmbracelet/bubbletea
	imports github.com/mattn/go-localereader: build constraints exclude all Go files in /home/ccp8964/H3399pc/lede/dl/go-mod-cache/github.com/mattn/go-localereader@v0.0.1

Building targets
../../../../../dl/go-mod-cache/github.com/!shelton!zhu/115driver@v1.0.22/pkg/driver/upload.go:20:2: no required module provides package github.com/SheltonZhu/115driver/pkg/crypto; to add it:
	go get github.com/SheltonZhu/115driver/pkg/crypto
../../../../../dl/go-mod-cache/github.com/gaoyb7/115drive-webdav@v0.1.8/115/api.go:10:2: no required module provides package github.com/gaoyb7/115drive-webdav/common; to add it:
	go get github.com/gaoyb7/115drive-webdav/common
../../../../../dl/go-mod-cache/github.com/gaoyb7/115drive-webdav@v0.1.8/115/client.go:16:2: no required module provides package github.com/gaoyb7/115drive-webdav/common/drive; to add it:
	go get github.com/gaoyb7/115drive-webdav/common/drive
../../../../../dl/go-mod-cache/github.com/pierrec/lz4/v4@v4.1.18/internal/lz4block/block.go:8:2: no required module provides package github.com/pierrec/lz4/v4/internal/lz4errors; to add it:
	go get github.com/pierrec/lz4/v4/internal/lz4errors
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/types.go:8:2: no required module provides package github.com/aws/aws-sdk-go/internal/sdkio; to add it:
	go get github.com/aws/aws-sdk-go/internal/sdkio
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/client/client.go:7:2: no required module provides package github.com/aws/aws-sdk-go/aws/client/metadata; to add it:
	go get github.com/aws/aws-sdk-go/aws/client/metadata
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/client/default_retryer.go:9:2: no required module provides package github.com/aws/aws-sdk-go/internal/sdkrand; to add it:
	go get github.com/aws/aws-sdk-go/internal/sdkrand
package github.com/alist-org/alist/v3
	imports github.com/alist-org/alist/v3/cmd
	imports github.com/alist-org/alist/v3/drivers
	imports github.com/alist-org/alist/v3/drivers/123
	imports github.com/aws/aws-sdk-go/aws/session
	imports github.com/aws/aws-sdk-go/aws/credentials/ssocreds
	imports github.com/aws/aws-sdk-go/service/sso
	imports github.com/aws/aws-sdk-go/aws/signer/v4
	imports github.com/aws/aws-sdk-go/private/protocol/rest
	imports github.com/aws/aws-sdk-go/private/protocol
	imports github.com/aws/aws-sdk-go/internal/sdkmath: build constraints exclude all Go files in /home/ccp8964/H3399pc/lede/dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/internal/sdkmath
../../../../../dl/go-mod-cache/github.com/aws/aws-sdk-go@v1.50.24/aws/ec2metadata/api.go:14:2: no required module provides package github.com/aws/aws-sdk-go/internal/sdkuri; to add it:
	go get github.com/aws/aws-sdk-go/internal/sdkuri
../../../../../dl/go-mod-cache/github.com/gin-gonic/gin@v1.9.1/binding/form_mapping.go:16:2: no required module provides package github.com/gin-gonic/gin/internal/json; to add it:
	go get github.com/gin-gonic/gin/internal/json
package github.com/alist-org/alist/v3
	imports github.com/alist-org/alist/v3/cmd
	imports github.com/charmbracelet/bubbles/table
	imports github.com/charmbracelet/bubbles/key
	imports github.com/charmbracelet/bubbletea
	imports github.com/mattn/go-isatty: build constraints exclude all Go files in /home/ccp8964/H3399pc/lede/dl/go-mod-cache/github.com/mattn/go-isatty@v0.0.19
../../../../../dl/go-mod-cache/github.com/rclone/rclone@v1.63.1/fs/fspath/path.go:12:2: no required module provides package github.com/rclone/rclone/fs/driveletter; to add it:
	go get github.com/rclone/rclone/fs/driveletter
../../../../../dl/go-mod-cache/github.com/rclone/rclone@v1.63.1/fs/rc/internal.go:21:2: no required module provides package github.com/rclone/rclone/lib/debug; to add it:
	go get github.com/rclone/rclone/lib/debug
../../../../../dl/go-mod-cache/github.com/multiformats/go-multihash@v0.2.3/registry.go:8:2: no required module provides package github.com/multiformats/go-multihash/register/all; to add it:
	go get github.com/multiformats/go-multihash/register/all
../../../../../dl/go-mod-cache/github.com/multiformats/go-multihash@v0.2.3/registry.go:9:2: no required module provides package github.com/multiformats/go-multihash/register/miniosha256; to add it:
	go get github.com/multiformats/go-multihash/register/miniosha256
../../../../../dl/go-mod-cache/github.com/libp2p/go-libp2p@v0.27.8/core/crypto/ecdsa.go:14:2: no required module provides package github.com/libp2p/go-libp2p/core/internal/catch; to add it:
	go get github.com/libp2p/go-libp2p/core/internal/catch
../../../../../dl/go-mod-cache/github.com/hirochachacha/go-smb2@v1.1.0/internal/msrpc/msrpc.go:7:2: no required module provides package github.com/hirochachacha/go-smb2/internal/utf16le; to add it:
	go get github.com/hirochachacha/go-smb2/internal/utf16le
../../../../../dl/go-mod-cache/github.com/blevesearch/bleve/v2@v2.3.10/geo/geo_s2plugin_impl.go:21:2: no required module provides package github.com/blevesearch/bleve/v2/util; to add it:
	go get github.com/blevesearch/bleve/v2/util
../../../../../dl/go-mod-cache/github.com/jackc/pgx/v5@v5.3.0/conn.go:11:2: no required module provides package github.com/jackc/pgx/v5/internal/anynil; to add it:
	go get github.com/jackc/pgx/v5/internal/anynil
../../../../../dl/go-mod-cache/github.com/pquerna/otp@v1.4.0/hotp/hotp.go:22:2: no required module provides package github.com/pquerna/otp/internal; to add it:
	go get github.com/pquerna/otp/internal
package github.com/alist-org/alist/v3
	imports github.com/alist-org/alist/v3/cmd
	imports github.com/charmbracelet/bubbles/table
	imports github.com/charmbracelet/bubbles/key
	imports github.com/charmbracelet/bubbletea
	imports github.com/mattn/go-localereader: build constraints exclude all Go files in /home/ccp8964/H3399pc/lede/dl/go-mod-cache/github.com/mattn/go-localereader@v0.0.1

make[3]: *** [Makefile:84: /home/ccp8964/H3399pc/lede/build_dir/target-aarch64_generic_musl/alist-3.33.0/.built] Error 1
make[3]: Leaving directory '/home/ccp8964/H3399pc/lede/feeds/kenzo/alist'
time: package/feeds/kenzo/alist/compile#0.77#0.63#0.80
    ERROR: package/feeds/kenzo/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/alist/compile] Error 1
make[2]: Leaving directory '/home/ccp8964/H3399pc/lede'
make[1]: *** [package/Makefile:110: /home/ccp8964/H3399pc/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ccp8964/H3399pc/lede'
make: *** [/home/ccp8964/H3399pc/lede/include/toplevel.mk:231：world] 错误 2
ccp8964@ccp8964:

**Comment by kenzok8** [comment]
这里不要提交issue,请到相关仓库提交 ，谢谢
