### ISSUE TITLE
mosdns上游仓库QiuSimons已经去掉了upx依赖

### ISSUE THREAD

**Issue by davidtall** [kenzok8/wall#4]
我看上游已经去掉了这个upx依赖， https://github.com/QiuSimons/openwrt-mos/commit/24002b01af7e109697269cb50b448d08d75edb42
大大提高了编译的成功率，但是 wall仓库还没有更新，所以不知道wall仓库中的mosdns 是从哪里同步过来的
@kenzok8

**Comment by kenzok8** [comment]
嗯，看到了，已修复
